cluster_name = "__CLUSTER_NAME__"
nodes = [1, 2, 3, 4, 5]
node_addrs = ["__NODE_ADDR_1__", "__NODE_ADDR_2__", "__NODE_ADDR_3__", "__NODE_ADDR_4__", "__NODE_ADDR_5__"]
initial_leader = 1
initial_flexible_quorum = { read_quorum_size = 3, write_quorum_size = 3 }
